[Server]
#监听地址
addr = ":10001"
#运行模式
debug = false

#账户
[[User]]
name = "Nail"
password= "ddd"
auth = ["read","delete","edit"]
dir = ["C:/"]

[[User]]
name = "Nail"
password= "ddd"
auth = ["read","delete","edit"]
dir = ["D:/","C:/"]


